/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package ui.admin;

import model.HospitalUserDirectory;
import model.HospitalUsers;

/**
 *
 * @author nishthapandya
 */
public class AddMembersJPanel extends javax.swing.JPanel {

    /** Creates new form AddMembersJPanel */
    public AddMembersJPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddHospitalMembers = new javax.swing.JLabel();
        lblAddMemberName = new javax.swing.JLabel();
        lblDateOfBirth = new javax.swing.JLabel();
        txtFieldMemberName = new javax.swing.JTextField();
        lblAddMemberRole = new javax.swing.JLabel();
        lblAddMemberOrganization = new javax.swing.JLabel();
        comboBoxOrganization = new javax.swing.JComboBox<>();
        lblAddMemberAddress = new javax.swing.JLabel();
        lblAddMemberCommunity = new javax.swing.JLabel();
        lblAddMemberPhoneNumber = new javax.swing.JLabel();
        lblAddMemberCity = new javax.swing.JLabel();
        txtFieldPhoneNumber = new javax.swing.JTextField();
        txtFieldAddress = new javax.swing.JTextField();
        txtFieldCommunity = new javax.swing.JTextField();
        txtFieldCity = new javax.swing.JTextField();
        lblAddMemberState = new javax.swing.JLabel();
        lblAddMemberZipCode = new javax.swing.JLabel();
        txtFieldState = new javax.swing.JTextField();
        txtFieldZipCode = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        comboBoxRole = new javax.swing.JComboBox<>();
        dateChooserDOB = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(252, 229, 229));

        lblAddHospitalMembers.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblAddHospitalMembers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddHospitalMembers.setText("Add Hospital Members");

        lblAddMemberName.setText("Name :");

        lblDateOfBirth.setText("Date Of Birth :");

        lblAddMemberRole.setText("Role :");

        lblAddMemberOrganization.setText("Organization :");

        comboBoxOrganization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "General", "Radiology", "Cardiology", "OBGYN", "Neurology", "Pediatrics", "Dermatology", "Pathology", "OPD", "Emergency" }));

        lblAddMemberAddress.setText("Address :");

        lblAddMemberCommunity.setText("Community :");

        lblAddMemberPhoneNumber.setText("Phone Number :");

        lblAddMemberCity.setText("City :");

        txtFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPhoneNumberActionPerformed(evt);
            }
        });

        lblAddMemberState.setText("State :");

        lblAddMemberZipCode.setText("Zip Code :");

        btnAdd.setText("Add Member");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        comboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "Doctor", "Intern Doctor", "Nurse", "Patient", "Chemist", "Pharmacist" }));
        comboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRoleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddHospitalMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddMemberRole)
                    .addComponent(lblDateOfBirth)
                    .addComponent(lblAddMemberName)
                    .addComponent(lblAddMemberPhoneNumber)
                    .addComponent(lblAddMemberOrganization))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxOrganization, 0, 1, Short.MAX_VALUE)
                    .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(txtFieldMemberName)
                    .addComponent(comboBoxRole, 0, 1, Short.MAX_VALUE)
                    .addComponent(dateChooserDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblAddMemberAddress)
                            .addGap(35, 35, 35))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblAddMemberCommunity)
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAddMemberState)
                                .addComponent(lblAddMemberZipCode))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddMemberCity)
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtFieldAddress)
                        .addComponent(txtFieldCommunity)
                        .addComponent(txtFieldState)
                        .addComponent(txtFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAddHospitalMembers)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMemberName)
                    .addComponent(txtFieldMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddMemberAddress)
                    .addComponent(txtFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDateOfBirth)
                        .addComponent(lblAddMemberCommunity)
                        .addComponent(txtFieldCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMemberRole)
                    .addComponent(lblAddMemberCity)
                    .addComponent(txtFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMemberOrganization)
                    .addComponent(comboBoxOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddMemberState)
                    .addComponent(txtFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddMemberPhoneNumber)
                    .addComponent(txtFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddMemberZipCode)
                    .addComponent(txtFieldZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPhoneNumberActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String role = (String) comboBoxRole.getSelectedItem();
        System.out.println("role : " + role);
        
        String organization = (String) comboBoxOrganization.getSelectedItem();
        System.out.println("organization : " + organization);
        
        HospitalUserDirectory hospDirectory = new HospitalUserDirectory();
        
        HospitalUsers hospUsers = hospDirectory.addNewHospitalUsers();
        hospUsers.setName(txtFieldMemberName.getText());
        hospUsers.setDOB(dateChooserDOB.getDateFormatString());
        hospUsers.setOrganization(comboBoxOrganization.getSelectedItem().toString());
        hospUsers.setPhoneNumber(txtFieldPhoneNumber.getText());
        hospUsers.setAddress(txtFieldAddress.getText());
        hospUsers.setCommunity(txtFieldCommunity.getText());
        hospUsers.setState(txtFieldState.getText());
        hospUsers.setZipcode(txtFieldZipCode.getText());
        hospUsers.setRole(comboBoxRole.getSelectedItem().toString());
        
        
        
                
//    String name;
//    String DOB;
//    String age;
//    String organization;
//    String phoneNumber;
//    String address;
//    String community;
//    String state;
//    String zipcode;
//    String role;
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRoleActionPerformed
        String role = comboBoxRole.getSelectedItem().toString();
        
        if(role.equals("Patient")) {
            comboBoxOrganization.setSelectedIndex(0);
            comboBoxOrganization.setEnabled(false);
        } else {
            comboBoxOrganization.setEnabled(true);
        }
        
    }//GEN-LAST:event_comboBoxRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> comboBoxOrganization;
    private javax.swing.JComboBox<String> comboBoxRole;
    private com.toedter.calendar.JDateChooser dateChooserDOB;
    private javax.swing.JLabel lblAddHospitalMembers;
    private javax.swing.JLabel lblAddMemberAddress;
    private javax.swing.JLabel lblAddMemberCity;
    private javax.swing.JLabel lblAddMemberCommunity;
    private javax.swing.JLabel lblAddMemberName;
    private javax.swing.JLabel lblAddMemberOrganization;
    private javax.swing.JLabel lblAddMemberPhoneNumber;
    private javax.swing.JLabel lblAddMemberRole;
    private javax.swing.JLabel lblAddMemberState;
    private javax.swing.JLabel lblAddMemberZipCode;
    private javax.swing.JLabel lblDateOfBirth;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldCity;
    private javax.swing.JTextField txtFieldCommunity;
    private javax.swing.JTextField txtFieldMemberName;
    private javax.swing.JTextField txtFieldPhoneNumber;
    private javax.swing.JTextField txtFieldState;
    private javax.swing.JTextField txtFieldZipCode;
    // End of variables declaration//GEN-END:variables

}
