/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.admin;

import java.sql.Connection;
import org.sqlite.SQLiteDataSource;
import ui.MainJFrame;

/**
 *
 * @author nishthapandya
 */
public class AdminJFrame extends javax.swing.JFrame {

    static SQLiteDataSource ds = null;
    static Connection sqliteConnection;

    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();

        try {
            ds = new SQLiteDataSource();
            System.out.println("ds");
            ds.setUrl("jdbc:sqlite:hospManagement.db");
            System.out.println("ds set");
            sqliteConnection = ds.getConnection();
            System.out.println("sqliteConnection set");
        } catch (Exception e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        bAllReceptionist = new javax.swing.JButton();
        bAllDoctors = new javax.swing.JButton();
        bAllPatients = new javax.swing.JButton();
        bAllNurses = new javax.swing.JButton();
        bLabAssistant = new javax.swing.JButton();
        bInternDoctors = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        bAddMembers = new javax.swing.JButton();
        bPharmacist = new javax.swing.JButton();
        bPathologist = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(193, 219, 219));

        bAllReceptionist.setText("Receptionist");
        bAllReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAllReceptionistMouseClicked(evt);
            }
        });
        bAllReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllReceptionistActionPerformed(evt);
            }
        });

        bAllDoctors.setText("Doctors");
        bAllDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllDoctorsActionPerformed(evt);
            }
        });

        bAllPatients.setText("Patients");
        bAllPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllPatientsActionPerformed(evt);
            }
        });

        bAllNurses.setText("Nurses");
        bAllNurses.setToolTipText("");
        bAllNurses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllNursesActionPerformed(evt);
            }
        });

        bLabAssistant.setText("Lab Assistant");
        bLabAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLabAssistantActionPerformed(evt);
            }
        });

        bInternDoctors.setText("Intern Doctors");
        bInternDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInternDoctorsActionPerformed(evt);
            }
        });

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        bAddMembers.setText("Add Members");
        bAddMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAddMembersMouseClicked(evt);
            }
        });
        bAddMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMembersActionPerformed(evt);
            }
        });

        bPharmacist.setText("Pharmacist");
        bPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPharmacistActionPerformed(evt);
            }
        });

        bPathologist.setText("Pathologist");
        bPathologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPathologistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bInternDoctors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLabAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllNurses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAddMembers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPharmacist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bPathologist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bAddMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(bAllReceptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bInternDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAllDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAllPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bAllNurses, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLabAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPharmacist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bPathologist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        jSplitPane.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(226, 255, 255));

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome");
        lblWelcome.setToolTipText("");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(lblWelcome)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(lblWelcome)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        jSplitPane.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane)
        );

        setSize(new java.awt.Dimension(1009, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAllReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAllReceptionistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAllReceptionistMouseClicked

    private void bAllReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllReceptionistActionPerformed
        // TODO add your handling code here:

        AllReceptionstJPanel receptionistPanel = new AllReceptionstJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(receptionistPanel);

    }//GEN-LAST:event_bAllReceptionistActionPerformed

    private void bAllDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllDoctorsActionPerformed
        AllDoctorsJPanel doctorsPanel = new AllDoctorsJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(doctorsPanel);
    }//GEN-LAST:event_bAllDoctorsActionPerformed

    private void bAllPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllPatientsActionPerformed
        // TODO add your handling code here:
        AllPatientsJPanel allPatients = new AllPatientsJPanel(ds,sqliteConnection);
        jSplitPane.setRightComponent(allPatients);
    }//GEN-LAST:event_bAllPatientsActionPerformed

    private void bAllNursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllNursesActionPerformed
        // TODO add your handling code here:
//        AllCommunitiesJPanel allCommunities = new AllCommunitiesJPanel(listOfCredentials, communityDirectory);
//        splitPane.setRightComponent(allCommunities);
    }//GEN-LAST:event_bAllNursesActionPerformed

    private void bLabAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLabAssistantActionPerformed
        
        AllLabAssistantJPanel labAssistant = new AllLabAssistantJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(labAssistant);
    }//GEN-LAST:event_bLabAssistantActionPerformed

    private void bInternDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInternDoctorsActionPerformed
        // TODO add your handling code here:
        AllInternDoctorsJPanel internDoctorsPanel = new AllInternDoctorsJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(internDoctorsPanel);
    }//GEN-LAST:event_bInternDoctorsActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        MainJFrame mainFrame = new MainJFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mainFrame.setVisible(true);
            }
        });
    }//GEN-LAST:event_bLogoutActionPerformed

    private void bAddMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAddMembersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAddMembersMouseClicked

    private void bAddMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMembersActionPerformed
        AddMembersJPanel addMembers = new AddMembersJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(addMembers);
    }//GEN-LAST:event_bAddMembersActionPerformed

    private void bPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPharmacistActionPerformed
        // TODO add your handling code here:
        AllPharmacistJPanel pharmacist = new AllPharmacistJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(pharmacist);
    }//GEN-LAST:event_bPharmacistActionPerformed

    private void bPathologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPathologistActionPerformed
        // TODO add your handling code here:
        AllPathologistJPanel pathologist = new AllPathologistJPanel(ds, sqliteConnection);
        jSplitPane.setRightComponent(pathologist);
        
    }//GEN-LAST:event_bPathologistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddMembers;
    private javax.swing.JButton bAllDoctors;
    private javax.swing.JButton bAllNurses;
    private javax.swing.JButton bAllPatients;
    private javax.swing.JButton bAllReceptionist;
    private javax.swing.JButton bInternDoctors;
    private javax.swing.JButton bLabAssistant;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bPathologist;
    private javax.swing.JButton bPharmacist;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
