/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pharmacy;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import org.sqlite.SQLiteDataSource;
import static pharmacy.Medicines.ps;
import static pharmacy.Medicines.sqliteConnection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import static pharmacy.Medicines.ps;
import static pharmacy.Medicines.sqliteConnection;

/**
 *
 * @author ADMIN
 */
public class Agents extends javax.swing.JFrame {

    /**
     * Creates new form Agents
     */
    public Agents() {
        initComponents();
        GetAllAgents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmacyLeftJPanel = new javax.swing.JPanel();
        agentJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        textFieldAgentAge = new javax.swing.JTextField();
        textFieldAgeId = new javax.swing.JTextField();
        textFieldAgentName = new javax.swing.JTextField();
        txtFieldAgentPass = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        btnAddAgent = new javax.swing.JButton();
        btnUpdateAgent = new javax.swing.JButton();
        btnDeleteAgent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AgentsJTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        textFieldAgentPhone = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        lblCompany = new javax.swing.JLabel();
        lblMedicines = new javax.swing.JLabel();
        lblSelling = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pharmacyLeftJPanel.setBackground(new java.awt.Color(0, 153, 0));

        agentJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE AGENTS");

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 153, 0));
        lblId.setText("ID");

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 153, 0));
        lblName.setText("NAME");

        lblAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAge.setForeground(new java.awt.Color(0, 153, 0));
        lblAge.setText("AGE");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 153, 0));
        lblPassword.setText("PASSWORD");

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(0, 153, 0));
        lblPhone.setText("PHONE");

        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(0, 153, 0));
        lblGender.setText("GENDER");

        textFieldAgentAge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldAgentAge.setForeground(new java.awt.Color(0, 153, 0));

        textFieldAgeId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldAgeId.setForeground(new java.awt.Color(0, 153, 0));

        textFieldAgentName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldAgentName.setForeground(new java.awt.Color(0, 153, 0));

        txtFieldAgentPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldAgentPass.setForeground(new java.awt.Color(0, 153, 0));

        comboGender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboGender.setForeground(new java.awt.Color(0, 153, 0));
        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        btnAddAgent.setBackground(new java.awt.Color(51, 204, 0));
        btnAddAgent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddAgent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAgent.setText("ADD");
        btnAddAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAgentMouseClicked(evt);
            }
        });

        btnUpdateAgent.setBackground(new java.awt.Color(51, 204, 0));
        btnUpdateAgent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdateAgent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateAgent.setText("UPDATE");
        btnUpdateAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateAgentMouseClicked(evt);
            }
        });

        btnDeleteAgent.setBackground(new java.awt.Color(51, 204, 0));
        btnDeleteAgent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDeleteAgent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteAgent.setText("DELETE");
        btnDeleteAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteAgentMouseClicked(evt);
            }
        });
        btnDeleteAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAgentActionPerformed(evt);
            }
        });

        AgentsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Phone", "Password", "Gender"
            }
        ));
        AgentsJTable.setRowHeight(25);
        AgentsJTable.setSelectionBackground(new java.awt.Color(0, 153, 0));
        AgentsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgentsJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(AgentsJTable);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("AGENTS LIST");

        textFieldAgentPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldAgentPhone.setForeground(new java.awt.Color(0, 153, 0));

        btnClear.setBackground(new java.awt.Color(51, 204, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout agentJPanelLayout = new javax.swing.GroupLayout(agentJPanel);
        agentJPanel.setLayout(agentJPanelLayout);
        agentJPanelLayout.setHorizontalGroup(
            agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentJPanelLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(agentJPanelLayout.createSequentialGroup()
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agentJPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnAddAgent)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateAgent)
                        .addGap(27, 27, 27)
                        .addComponent(btnDeleteAgent)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addGroup(agentJPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(agentJPanelLayout.createSequentialGroup()
                                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAgeId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(agentJPanelLayout.createSequentialGroup()
                                .addComponent(lblAge)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldAgentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96)
                        .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhone)
                            .addComponent(lblPassword)
                            .addComponent(lblGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldAgentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agentJPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        agentJPanelLayout.setVerticalGroup(
            agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agentJPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAgeId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId)
                    .addComponent(lblPhone)
                    .addComponent(textFieldAgentPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(textFieldAgentName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword)
                    .addComponent(txtFieldAgentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAgentAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAge)
                    .addComponent(lblGender)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(agentJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCompany.setBackground(new java.awt.Color(255, 255, 255));
        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(255, 255, 255));
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCompany.setText("COMPANY");
        lblCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCompanyMouseClicked(evt);
            }
        });

        lblMedicines.setBackground(new java.awt.Color(255, 255, 255));
        lblMedicines.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMedicines.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicines.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedicines.setText("MEDICINES");
        lblMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMedicinesMouseClicked(evt);
            }
        });

        lblSelling.setBackground(new java.awt.Color(255, 255, 255));
        lblSelling.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelling.setForeground(new java.awt.Color(255, 255, 255));
        lblSelling.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelling.setText("SELLING");
        lblSelling.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pharmacyLeftJPanelLayout = new javax.swing.GroupLayout(pharmacyLeftJPanel);
        pharmacyLeftJPanel.setLayout(pharmacyLeftJPanelLayout);
        pharmacyLeftJPanelLayout.setHorizontalGroup(
            pharmacyLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                .addGroup(pharmacyLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pharmacyLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedicines)
                            .addComponent(lblCompany)))
                    .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblSelling)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(agentJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        pharmacyLeftJPanelLayout.setVerticalGroup(
            pharmacyLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                .addGroup(pharmacyLeftJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pharmacyLeftJPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(agentJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pharmacyLeftJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pharmacyLeftJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(872, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAgentMouseClicked

        try {
            ps = new SQLiteDataSource();
            
            ps.setUrl("jdbc:sqlite:hospManagement.db");
            sqliteConnection = ps.getConnection();
            String commandagent = "insert into agent (AgeId, AgeName, AgePhone, AgeAge, AgePass, AgeGend ) values (?,?,?,?,?,?)";

            PreparedStatement p2p = sqliteConnection.prepareStatement(commandagent);

            p2p.setInt(1, Integer.valueOf(textFieldAgeId.getText()));
            p2p.setString(2, textFieldAgentName.getText());
            p2p.setInt(3, Integer.valueOf(textFieldAgentAge.getText()));
            p2p.setString(4, textFieldAgentPhone.getText());
            p2p.setString(5, txtFieldAgentPass.getText());
            p2p.setString(6, comboGender.getSelectedItem().toString());

            boolean output = p2p.execute();
            
            JOptionPane.showMessageDialog(this, "Agent Successfully Added!");
            sqliteConnection.close();
            GetAllAgents();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnAddAgentMouseClicked

    private void btnUpdateAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateAgentMouseClicked

        if (textFieldAgeId.getText().isEmpty() || textFieldAgentName.getText().isEmpty() || textFieldAgentAge.getText().isEmpty() || textFieldAgentPhone.getText().isEmpty() || txtFieldAgentPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information about Agent");
        }
        else
        {
            try {
                ps = new SQLiteDataSource();
            
                ps.setUrl("jdbc:sqlite:hospManagement.db");
                sqliteConnection = ps.getConnection();
                String id = textFieldAgeId.getText();

                String queryUpdateAgent = "update agent set AgeName = '" + textFieldAgentName.getText() + "'" + ",AgeAge = " + textFieldAgentAge.getText() + "" + ",AgePhone= " + textFieldAgentPhone.getText() + "" + ",AgePass = '" + txtFieldAgentPass.getText() + "'" + ",AgeGend = '" + comboGender.getSelectedItem().toString() + "'" + "where AgeId = " + id;

                PreparedStatement p2p = sqliteConnection.prepareStatement(queryUpdateAgent);
                boolean output = p2p.execute();
                
                GetAllAgents();
                JOptionPane.showMessageDialog(this, "Agent Successfully Updated!");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnUpdateAgentMouseClicked

    private void btnDeleteAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAgentMouseClicked

        if (textFieldAgeId.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter ID of The Agent To Be Deleted....");
        }
        else
        {
            try {
                ps = new SQLiteDataSource();
            
                ps.setUrl("jdbc:sqlite:hospManagement.db");
                sqliteConnection = ps.getConnection();
                String id = textFieldAgeId.getText();
                String queryDeleteAgent = "Delete from agent where AgeId = " + id;
                
                PreparedStatement p2p = sqliteConnection.prepareStatement(queryDeleteAgent);
                boolean output = p2p.execute();
                
                GetAllAgents();
                JOptionPane.showMessageDialog(this, "Agent Successfully Deleted!");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteAgentMouseClicked

    private void AgentsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgentsJTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)AgentsJTable.getModel();
        int myIndex = AgentsJTable.getSelectedRow();
        textFieldAgeId.setText(model.getValueAt(myIndex, 0).toString());
        textFieldAgentName.setText(model.getValueAt(myIndex, 1).toString());
        textFieldAgentAge.setText(model.getValueAt(myIndex, 2).toString());
        textFieldAgentPhone.setText(model.getValueAt(myIndex, 3).toString());
        txtFieldAgentPass.setText(model.getValueAt(myIndex, 4).toString());
    }//GEN-LAST:event_AgentsJTableMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked

        textFieldAgeId.setText("");
        textFieldAgentName.setText("");
        textFieldAgentAge.setText("");
        textFieldAgentPhone.setText("");
        txtFieldAgentPass.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void lblCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCompanyMouseClicked
        new Company().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCompanyMouseClicked

    private void lblMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMedicinesMouseClicked
        new Medicines().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblMedicinesMouseClicked

    private void lblSellingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellingMouseClicked
        new Selling().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSellingMouseClicked

    private void btnDeleteAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AgentsJTable;
    private javax.swing.JPanel agentJPanel;
    private javax.swing.JButton btnAddAgent;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDeleteAgent;
    private javax.swing.JButton btnUpdateAgent;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMedicines;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSelling;
    private javax.swing.JPanel pharmacyLeftJPanel;
    private javax.swing.JTextField textFieldAgeId;
    private javax.swing.JTextField textFieldAgentAge;
    private javax.swing.JTextField textFieldAgentName;
    private javax.swing.JTextField textFieldAgentPhone;
    private javax.swing.JTextField txtFieldAgentPass;
    // End of variables declaration//GEN-END:variables

    private void GetAllAgents() {
        try {
           ps = new SQLiteDataSource();
            
           ps.setUrl("jdbc:sqlite:hospManagement.db");
           sqliteConnection = ps.getConnection();
        
           String command = "Select * from agent";
           Statement p2p = sqliteConnection.createStatement();
           ResultSet rs = p2p.executeQuery(command);
           AgentsJTable.setModel(DbUtils.resultSetToTableModel(rs));

           
            
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
}
