/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UILaboratory;

import Laboratory.LabInventory;
import java.sql.Connection;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import org.sqlite.SQLiteDataSource;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shubhdashail
 */
public class Add_lab_testsUI extends javax.swing.JPanel {

    private static LabInventory lab_invent;

    /**
     * Creates new form ViewPatientSample
     */
    public Add_lab_testsUI(LabInventory lab_inventory) {
        initComponents();
        this.lab_invent = lab_inventory;
    }
    static Connection sqliteConnection;
    static Statement statement;
    static SQLiteDataSource ps = null;
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;

    public boolean validatedata() {
        if ("".equals(txtPatientName.getText())) {
            JOptionPane.showMessageDialog(this, "Enter patient's name");
            return false;
        }
        if (!txtPatientName.getText().matches("[a-zA-Z ]+")) {
            JOptionPane.showMessageDialog(this, "Enter Proper Name.");
            return false;
        }
        if (!txtPatientID.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Enter proper case no.");
            return false;
        }
        if ("".equals(txtDoctorName.getText())) {
            JOptionPane.showMessageDialog(this, "Enter Doctor's name");
            return false;
        }
        if (!txtBloodGroup.getText().matches("(A|B|AB|O)(\\+|-)")) {
            JOptionPane.showMessageDialog(this, "Enter a blood group");
            return false;
        }

        if (!txtAge.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(this, "Enter patient's age");
            return false;
        }
        return true;
    }

    private void getTest() {
        try {
            ps = new SQLiteDataSource();

            ps.setUrl("jdbc:sqlite:hospManagement.db");
            sqliteConnection = ps.getConnection();

            String command = "Select * from labtest";
            Statement p2p = sqliteConnection.createStatement();
            ResultSet rs = p2p.executeQuery(command);
            tbladd_test.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
    
    private void getPatientHist(){
        try {
            ps = new SQLiteDataSource();

            ps.setUrl("jdbc:sqlite:hospManagement.db");
            sqliteConnection = ps.getConnection();

            String command = "Select * from appointment";
            Statement p2p = sqliteConnection.createStatement();
            ResultSet rs = p2p.executeQuery(command);
//            tblPatientHist.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnAddTest = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtComboSpecimen = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbladd_test = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        txtBloodGroup = new javax.swing.JTextField();
        txtComboGender = new javax.swing.JComboBox<>();
        txtComboDepartment = new javax.swing.JComboBox<>();
        txtPatientID = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        DeletejButton = new javax.swing.JButton();
        UpdatejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arima Koshi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Lab tests");

        jLabel2.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor Name:");

        jLabel4.setFont(new java.awt.Font("Arima Koshi", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");

        jLabel6.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Department:");

        jLabel5.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Blood group:");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        btnAddTest.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        btnAddTest.setText("Add Tests to be done for this patient");
        btnAddTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTestMouseClicked(evt);
            }
        });
        btnAddTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTestActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PatientID:");

        jLabel8.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Specimen:");

        txtComboSpecimen.setFont(new java.awt.Font("Arima Koshi", 0, 12)); // NOI18N
        txtComboSpecimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "MRI(Radiology)", "MRA(Radiology)", "X-Ray(Radiology)", "PET Scan(Radiology)", "Ultrasound(Radiology)", "Complete Blood count(Pathology)", "Urine culture", "Stool culture", "Lipid panel", "Liver panel", "Sonogram", " " }));

        tbladd_test.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tbladd_test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pateint_ID", "Name", "Blood_Group", "Department", "Tests"
            }
        ));
        tbladd_test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbladd_testMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbladd_test);

        jLabel9.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender:");

        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });

        txtComboGender.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        txtComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Male", "Female" }));

        txtComboDepartment.setFont(new java.awt.Font("Arima Koshi", 0, 13)); // NOI18N
        txtComboDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "General", "OBGYN", "Neurology", "Paediatric", "Cardiology", "Dermatology", "Radiology", " " }));

        jButtonClear.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonClearMouseClicked(evt);
            }
        });
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        DeletejButton.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        DeletejButton.setText("Delete");
        DeletejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletejButtonMouseClicked(evt);
            }
        });

        UpdatejButton.setFont(new java.awt.Font("Arima Koshi", 0, 14)); // NOI18N
        UpdatejButton.setText("Update");
        UpdatejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatejButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBloodGroup)
                                    .addComponent(txtDoctorName))
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(txtComboSpecimen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(txtComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(UpdatejButton)
                        .addGap(46, 46, 46)
                        .addComponent(jButtonClear)
                        .addGap(44, 44, 44)
                        .addComponent(DeletejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnAddTest)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComboDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtComboSpecimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(DeletejButton)
                    .addComponent(UpdatejButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnAddTest)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void tbladd_testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbladd_testMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tbladd_test.getModel();
        int myIndex = tbladd_test.getSelectedRow();
        txtPatientID.setText(model.getValueAt(myIndex, 0).toString());
        txtPatientName.setText(model.getValueAt(myIndex, 1).toString());
        txtBloodGroup.setText(model.getValueAt(myIndex, 2).toString());
        txtComboDepartment.setSelectedItem(model.getValueAt(myIndex,3).toString());
        txtComboSpecimen.setSelectedItem(model.getValueAt(myIndex,4).toString());
        
        
    }//GEN-LAST:event_tbladd_testMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonClearMouseClicked
        // TODO add your handling code here:                                             

        if (txtPatientID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Enter Patient ID To Be Deleted....");
        }
        else
        {
            try {
                ps = new SQLiteDataSource();
            
                ps.setUrl("jdbc:sqlite:hospManagement.db");
                sqliteConnection = ps.getConnection();
                String id = txtPatientID.getText();
                String query = "Delete from labtest where Pateint_ID = " + id;
                
                PreparedStatement p2p = sqliteConnection.prepareStatement(query);
                boolean output = p2p.execute();


                getTest();
                JOptionPane.showMessageDialog(this, "Test Successfully Deleted!");

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    
    }//GEN-LAST:event_jButtonClearMouseClicked

    private void btnAddTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTestActionPerformed

    private void btnAddTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTestMouseClicked
        // TODO add your handling code here;

        try {
            
            ps = new SQLiteDataSource();
            
            ps.setUrl("jdbc:sqlite:hospManagement.db");
            sqliteConnection = ps.getConnection();
            String command = "insert into labtest (Pateint_ID, DoctorName, Name, Age, gender, Blood_Group, Tests, Department ) values (?,?,?,?,?,?,?,?)";

            PreparedStatement p2p = sqliteConnection.prepareStatement(command);
            System.out.println(txtBloodGroup.getText());
            
            p2p.setInt(1, Integer.valueOf(txtPatientID.getText()));
            p2p.setString(2, txtDoctorName.getText());
            p2p.setString(3, txtPatientName.getText());
            p2p.setInt(4, Integer.valueOf(txtAge.getText()));
            p2p.setString(5, ((JTextField)txtComboGender.getEditor().getEditorComponent()).getText());
            p2p.setString(6, txtBloodGroup.getText());
            p2p.setString(7,  ((JTextField)txtComboSpecimen.getEditor().getEditorComponent()).getText());
            p2p.setString(8, ((JTextField)txtComboDepartment.getEditor().getEditorComponent()).getText());
            
            
            
            
            boolean output = p2p.execute();
            JOptionPane.showMessageDialog(this, "Tests Successfully Added!");
            sqliteConnection.close();
            getTest();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnAddTestMouseClicked

    private void DeletejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletejButtonMouseClicked
        // TODO add your handling code here:
        txtPatientName.setText("");
        txtPatientID.setText("");
        txtDoctorName.setText("");
        txtBloodGroup.setText("");
        txtAge.setText("");
    }//GEN-LAST:event_DeletejButtonMouseClicked

    private void UpdatejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatejButtonMouseClicked
        // TODO add your handling code here:
        if (txtPatientID.getText().isEmpty() || txtAge.getText().isEmpty() || txtPatientName.getText().isEmpty() || txtDoctorName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Missing Information about laboratory");
        }
        else
        {
            try {
                ps = new SQLiteDataSource();
            
                ps.setUrl("jdbc:sqlite:hospManagement.db");
                sqliteConnection = ps.getConnection();
                String id = txtPatientID.getText();
                String queryUpdate = "update labtest set Name = '" + txtPatientName.getText() + "',Blood_Group = '" + txtBloodGroup.getText() + "',Department= '" + txtComboDepartment.getSelectedItem() + "',Age = " + txtAge.getText() + ",gender = '" + txtComboGender.getSelectedItem() + "',Tests = '" + txtComboSpecimen.getSelectedItem() + "' where Pateint_ID = " + id;

                PreparedStatement p2p = sqliteConnection.prepareStatement(queryUpdate);
                boolean output = p2p.execute();

                JOptionPane.showMessageDialog(this, "Laboratory Successfully Updated!");
                sqliteConnection.close();
                getTest();

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_UpdatejButtonMouseClicked

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeletejButton;
    private javax.swing.JButton UpdatejButton;
    private javax.swing.JButton btnAddTest;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbladd_test;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBloodGroup;
    private javax.swing.JComboBox<String> txtComboDepartment;
    private javax.swing.JComboBox<String> txtComboGender;
    private javax.swing.JComboBox<String> txtComboSpecimen;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
