/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

/**
 *
 * @author nishthapandya
 */
public class AdminJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        bAllReceptionist = new javax.swing.JButton();
        bAllDoctors = new javax.swing.JButton();
        bAllPatients = new javax.swing.JButton();
        bAllNurses = new javax.swing.JButton();
        bChemist = new javax.swing.JButton();
        bInternDoctors = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(193, 219, 219));

        bAllReceptionist.setText("Receptionist");
        bAllReceptionist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAllReceptionistMouseClicked(evt);
            }
        });
        bAllReceptionist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllReceptionistActionPerformed(evt);
            }
        });

        bAllDoctors.setText("Doctors");
        bAllDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllDoctorsActionPerformed(evt);
            }
        });

        bAllPatients.setText("Patients");
        bAllPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllPatientsActionPerformed(evt);
            }
        });

        bAllNurses.setText("Nurses");
        bAllNurses.setToolTipText("");
        bAllNurses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAllNursesActionPerformed(evt);
            }
        });

        bChemist.setText("Chemist");
        bChemist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChemistActionPerformed(evt);
            }
        });

        bInternDoctors.setText("Intern Doctors");
        bInternDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInternDoctorsActionPerformed(evt);
            }
        });

        bLogout.setText("Logout");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAllPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAllReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bChemist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(bAllNurses, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bInternDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(bAllReceptionist, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bAllDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bAllPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(bAllNurses, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bChemist, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(bInternDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setBackground(new java.awt.Color(226, 255, 255));

        lblWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome");
        lblWelcome.setToolTipText("");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(lblWelcome)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(lblWelcome)
                .addContainerGap(481, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAllReceptionistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAllReceptionistMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bAllReceptionistMouseClicked

    private void bAllReceptionistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllReceptionistActionPerformed
        // TODO add your handling code here:

//        AllHospitalsJPanel allHospitals = new AllHospitalsJPanel(listOfCredentials, hospDirectory);
//        splitPane.setRightComponent(allHospitals);
    }//GEN-LAST:event_bAllReceptionistActionPerformed

    private void bAllDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllDoctorsActionPerformed
        // TODO add your handling code here:
//        AllDoctorsJPanel allDoctors = new AllDoctorsJPanel(listOfCredentials, docDirectory);
//        splitPane.setRightComponent(allDoctors);
    }//GEN-LAST:event_bAllDoctorsActionPerformed

    private void bAllPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllPatientsActionPerformed
        // TODO add your handling code here:
//        AllPatientsJPanel allPatients = new AllPatientsJPanel(listOfCredentials, patientDirectory);
//        splitPane.setRightComponent(allPatients);
    }//GEN-LAST:event_bAllPatientsActionPerformed

    private void bAllNursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAllNursesActionPerformed
        // TODO add your handling code here:
//        AllCommunitiesJPanel allCommunities = new AllCommunitiesJPanel(listOfCredentials, communityDirectory);
//        splitPane.setRightComponent(allCommunities);
    }//GEN-LAST:event_bAllNursesActionPerformed

    private void bChemistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChemistActionPerformed
        // TODO add your handling code here:
//        dispose();
//        MainJFrame mainFrame = new MainJFrame(listOfCredentials);
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                mainFrame.setVisible(true);
//            }
//        });
    }//GEN-LAST:event_bChemistActionPerformed

    private void bInternDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInternDoctorsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bInternDoctorsActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAllDoctors;
    private javax.swing.JButton bAllNurses;
    private javax.swing.JButton bAllPatients;
    private javax.swing.JButton bAllReceptionist;
    private javax.swing.JButton bChemist;
    private javax.swing.JButton bInternDoctors;
    private javax.swing.JButton bLogout;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
